services:
  db_postgres:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raven
    volumes:
      - db_postgres:/var/lib/postgresql/data

volumes:
  db_postgres:
    driver: local
