services:
  db_postgres:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5455:5432 # Map host port 5455 to container port 5432
    environment:
      POSTGRES_USER: postgres # Correct environment variable name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raven
    volumes:
      - db_postgres:/var/lib/postgresql/data

volumes:
  db_postgres:
    driver: local
